---

driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu/xenial64
  - name: centos/7
  - name: debian/jessie64

suites:
  - name: default
    run_list:
      - recipe[cas_haproxy::default]
    attributes:
      cas_haproxy:
        stats:
          enabled: true
          auth: 'username:password'
        sites:
          - id: blog
            frontend:
              bind_port: 6061
              target_urls:
                - example.com
                - blog.example.com
            backend:
              balance_strategy: leastconn
              servers:
                - id: web1
                  address: web1.local
                - id: web2
                  address: web2.local
                - address: snowflake.local
          - id: wiki
            frontend:
              target_urls:
                - wiki.example.com
            backend:
              servers:
                - id: web3
                  address: web3.local
